image: node:latest

stages:
  - test
  - deploy
  - release

"Test":
  stage: test
  allow_failure: false
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
  before_script:
    - npm ci
  script:
    - npm run tsc

pages:
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm ci
    - npm run build
    - rm -rf ./public
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master

"Release":
  stage: release
  allow_failure: false
  before_script:
    - git config --global user.email "bot@_.com"
    - git config --global user.name "Auto Bot"
    - git clone http://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/codogo-b/back-home-safe.git &> /dev/null
    - git checkout -qf master
    - cd back-home-safe
    - npm ci
  only:
    refs:
      - master
    variables:
      - $GIT_LAB_USERNAME != null
      - $PERSONAL_ACCESS_TOKEN != null
  environment:
    name: production
  script:
    - npm run release
    - git push http://${GIT_LAB_USERNAME}:${PERSONAL_ACCESS_TOKEN}@gitlab.com/codogo-b/back-home-safe.git --verbose --no-verify --follow-tags HEAD:master
