stages:
  - test
  - page

"Test":
  stage: test
  image: node:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - node_modules/
  before_script:
    - npm ci
  script:
    - npm run tsc

"Page":
  stage: page
  image: node:latest
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .npm/
      - node_modules/

  script:
    - npm ci
    - npm run build
    - rm -rf ./public
    - mv ./build ./public
  artifacts:
    paths:
      - public
  only:
    - master
